<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 18/5/8
 * Time: ÏÂÎç4:09
 */

namespace app\home\controller;


use think\Controller;

class IndexController extends Controller {

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction(){
        file_grabbing("http://kaijiang.500.com/shtml/ssq/03001.shtml");
        //return $this->fetch();
    }
}