<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 18/5/8
 * Time: 下午4:09
 */

namespace app\home\controller;


use app\home\model\TicketModel;
use think\Config;
use think\Controller;
use think\Db;

class IndexController extends Controller {

    protected function _initialize() {
        $this->beforeActionList = ['grabbing'];


        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    protected function grabbing(){
        $config = Config::get('double_chromosphere');
        $ball_url = $config['curl_url'];
        $ball_year = $config['cur_year'];;
        $ball_no = $config['cur_number'];
        $fixt = $config['curl_html'];

        $cur_year = date('y', time());
        if($ball_year != $cur_year){
            $ball_year = $cur_year;
        }

        $no = substr("0" . $ball_year, -2) . substr("000" . $ball_no, -3);
        $model = new TicketModel();
        $info = $model->where('issue',$no)->find();
        if(empty($info)){
            $curl_url = $ball_url . $no . $fixt;
            $ball = file_grabbing($curl_url);
            if(!empty($ball)){
                if(intval($ball[0]) > 0 && intval($ball[1]) > 0 && intval($ball[2]) > 0 && intval($ball[3]) > 0 &&
                    intval($ball[4]) > 0 && intval($ball[5]) > 0 && intval($ball[6]) > 0) {

                    $data = array(
                        'issue' => $no,
                        'identifier' => $ball_no,
                        'red_one' => $ball[0],
                        'red_two' => $ball[1],
                        'red_three' => $ball[2],
                        'red_four' => $ball[3],
                        'red_five' => $ball[4],
                        'red_six' => $ball[5],
                        'blue' => $ball[6],
                        'lotteries' => $ball[0] . $ball[1] . $ball[2] . $ball[3] . $ball[4] . $ball[5] . $ball[6]
                    );

                    $model->save($data);

                    //修改参数
                    $file = APP_PATH . 'home/config.php';
                    set_config($file, array('cur_year' => $ball_year, 'cur_number' => ($ball_no + 1)));
                }
            }
        }
        unset($model,$info);
    }

    public function indexAction(){
        //判断是否有相同的号码
        $sames = Db::query('select lotteries,count(id) as count from ticket group by lotteries having count > 1');

        //获取到和当前期数相同的以前的所有记录
        $model = new TicketModel();
        $config = Config::get('double_chromosphere');
        $curList = $model->fetchSql(false)->where(array('identifier' => $config['cur_number']))->order(array('id asc'))->select();
        $this->assign('list',$curList);
        return $this->fetch();
    }

    public function setLotteryAction(){
        set_time_limit(0);
        $model = new TicketModel();
        $list = $model->fetchSql(false)->order(array('id asc'))->select();
        $update = array();
        foreach ($list as $key => $item){
            $lottery = $item['red_one'] . $item['red_two'] . $item['red_three'] . $item['red_four'] . $item['red_five'] . $item['red_six'] . $item['blue'];
            $update[] = ['id' => $item['id'],'lotteries' => $lottery];
        }
        if(!empty($update)){
            $model->isUpdate()->saveAll($update);
        }

        $this->success('设置成功','Index/index');
    }
}