<?php
/**
 * Created by PhpStorm.
 * User: appleimac
 * Date: 18/5/8
 * Time: ÏÂÎç4:09
 */

namespace app\home\controller;


use think\Config;
use think\Controller;

class IndexController extends Controller {

    protected function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction(){
        $url = Config::get('double_chromosphere.curl_url');
        $year = Config::get('double_chromosphere.cur_year');
        $number = Config::get('double_chromosphere.cur_number');
        
        $curYear = date('y', time());



        $ball = file_grabbing("http://kaijiang.500.com/shtml/ssq/03001.shtml");
        //return $this->fetch();
    }
}